### ISSUE TITLE
OCPP 1.6 compatibility

### ISSUE THREAD

**Issue by ak-junior** [RWTH-i5-IDSG/steve-plugsurfing#8]
Hello, 
I all-ready tried Steve, and it is pretty awesome. I have a question concerning OCPP 1.6 compatibility.

OCPP 1.6 is very near from OCPP 1.5-J. New features concern mainly smart-charging. As specified in protocol definition, only "core" features are mandatory  and we allready have them in Steve (1.5).

So, I would like to know if it is possible to update Steve and let it accept OCCP 1.6 charging stations and consider them like a 1.5(-J) charging station. 

I am pretty sure there is something to do in /src/main/java/de/rwth/idsg/steve/ocpp/OcppVersion.java but my tests did not work.

Regards

**Comment by f-ohler** [comment]
It's great to see the SteVe community grow. Thanks for the nice words.

OCPP 1.6 really seems pretty close to OCPP 1.5 and e.g. JSON is already supported.
Yet, this repository focuses on the compatibility with plugsurfing (as opposed to the core at https://github.com/RWTH-i5-IDSG/steve).
Thus, support for the new OCPP version should first be implemented in the core.
We would be very interested to see what you already tried and encourage you to open a pull request at the core repository.
As a follow-up we can merge the changes here and look at possible compatibility issues concerning plugsurfing.

Since this is an open-source project, any help is always welcome.

**Comment by goekay** [comment]
this issue is related to the core and can be further discussed at https://github.com/RWTH-i5-IDSG/steve/issues/29
